gkename: cluster-1
initial_node_count: 2
machine_type: n2-standart-2
disk_size_gb: 100
zone: europe-west4-a
project: alert-palace-304914
auth_kind: serviceaccount
service_account_file: account.json
#gke node pool
npname: gke-pool
np_initial_node_count: 3
