apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress-nginx-ingress
  name: ingress-exporter
  namespace: default
spec:
  ports:
  - name: http
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: nginx-ingress-nginx-ingress
  sessionAffinity: None
  type: ClusterIP

