---
- name: create accounts file from template
  template:
    src: account.json.j2
    dest: ./account.json

- name: create a cluster
  remote_user: "{{ r_user }}"
  gcp_container_cluster:
    name: "{{ gkename }}"
    initial_node_count: "{{ initial_node_count }}"
    master_auth:
      username: "{{ username }}"
      password: "{{ password }}"
    node_config:
      machine_type: "{{ machine_type }}"
      disk_size_gb: "{{ disk_size_gb }}"
    zone: "{{ zone }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: present
  register: cluster

- name: create node pool
  gcp_container_node_pool:
    name: "{{ npname }}"
    initial_node_count: "{{ np_initial_node_count }}"
    management:
      auto_repair: true
      auto_upgrade: true
    cluster: "{{ cluster }}"
    zone: "{{ zone }}"
    project: "{{ project }}"
    auth_kind: "{{ auth_kind }}"
    service_account_file: "{{ service_account_file }}"
    scopes:
      - https://www.googleapis.com/auth/cloud-platform
    state: present

- name: add cluster in context
  shell:  /home/mj/Documents/google-cloud-sdk/bin/gcloud container clusters get-credentials {{ gkename }}


