- name: get ip cluster
  #shell: kubectl get ep | grep kubernetes| awk '{match($2,"[0-9]+.[0-9]+.[0-9]+.[0-9]+",a)}END{print a[0]}'
  shell: kubectl get svc -n ingress | grep nginx-ingress-controller | awk '{match($4,"[0-9]+.[0-9]+.[0-9]+.[0-9]+",a)}END{print a[0]}'
  register: ip_addr

- name: debug 
  debug:
    msg: "{{ ip_addr.stdout }}"

- name: create frontend vlaues from template
  template:
    src: values.yaml.j2
    dest: ./hipster-shop/charts/frontend/values.yaml


  #- name: Deploy Grafana chart from local path
  #  remote_user: "{{ r_user }}"
  #  community.kubernetes.helm:
  #    name: hipster-shop-site
  #    release_namespace: default
  #    chart_ref: ./hipster-shop
