- name: get ip cluster 
  shell: kubectl get svc -n ingress | grep nginx-ingress-nginx-ingress | awk '{match($4,"[0-9]+.[0-9]+.[0-9]+.[0-9]+",a)}END{print a[0]}'
  register: ip_addr
  until: ip_addr.stdout != ""
  retries: 10
  delay: 30

- name: debug 
  debug:
    msg: "{{ ip_addr.stdout }}"

- name: create frontend vlaues from template
  template:
    src: values.yaml.j2
    dest: ./hipster-shop/charts/frontend/values.yaml


- name: Deploy hipster-shop
  remote_user: "{{ r_user }}"
  community.kubernetes.helm:
    name: hipster-shop-site
    release_namespace: default
    chart_ref: ./hipster-shop
