- name: Create ingress ns
  shell: kubectl create ns ingress
  ignore_errors: true

- name: create secret from template
  template:
    src: secret-ingress.json.j2
    dest: ./01-secrets.json

- name: apply secret
  shell: kubectl apply -f 01-secrets.json

- name: remove secret
  file:
    path: ./01-secrets.json
    state: absent

- name: Deploy nginx-ingress
  remote_user: "{{ r_user }}"
  community.kubernetes.helm:
    chart_repo_url: https://helm.nginx.com/stable
    name: nginx-ingress 
    release_namespace: default
    chart_ref: nginx-ingress

- name: get ip cluster 
  shell: kubectl get svc -n default | grep nginx-ingress-nginx-ingress | awk '{match($4,"[0-9]+.[0-9]+.[0-9]+.[0-9]+",a)}END{print a[0]}'
  register: ip_addr
  until: ip_addr.stdout != ""
  retries: 10
  delay: 30

- name: debug 
  debug:
    msg: "{{ ip_addr.stdout }}"

- name: create frontend vlaues from template
  template:
    src: values.yaml.j2
    dest: ./hipster-shop/charts/frontend/values.yaml


- name: Deploy hipster-shop
  remote_user: "{{ r_user }}"
  community.kubernetes.helm:
    name: hipster-shop-site
    release_namespace: default
    chart_ref: ./hipster-shop
