- name: Create ingress ns 
  shell: kubectl create ns ingress
  ignore_errors: true

- name: create secret from template
  template:
    src: secret-ingress.json.j2
    dest: ./01-secrets.json

- name: apply secret
  shell: kubectl apply -f 01-secrets.json

- name: remove secret
  file:
    path: ./01-secrets.json
    state: absent

- name: create values from template
  template:
    src: ingress-values.yaml.j2
    dest: ./ingress-values.yaml

- name: Deploy nginx-ingress
  remote_user: "{{ r_user }}"
  community.kubernetes.helm:
    chart_repo_url: https://helm.nginx.com/stable
    name: nginx-ingress 
    release_namespace: default
    chart_ref: nginx-ingress
    values_files: ./ingress-values.yaml

- name: remove values
  file:
    path: ./ingress-values.yaml
    state: absent

- name: apply metricService 
  shell: kubectl apply -f ./roles/deploy_ingress/files/svc-ingress-exporter.yaml 
