apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - grafana.{{ .Values.ip }}.nip.io
      secretName: ingress-tls
  rules:
    - host: grafana.{{ .Values.ip }}.nip.io
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus-grafana 
            servicePort: 80
